Advanced Data Structures 

1. Numpy (Ref:A52_dsNP)
similar to list, but items to be one type (so less memory required to store and manipulate) more functions available helps in matrix computations

In [4]:
#%% #numpy - array - same data type - numerical python
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [7]:
import numpy
print(numpy.array([10,40])) #list to numpy array
print(numpy.array([list1])) #list inside a list

[10 40]
[[1 2 3 4]]


In [3]:
import numpy as np #np is alias
print(np.__version__)

1.24.3


In [4]:
np.arange(1,200,5)  #start, stop, setp

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196])

In [5]:
x=np.arange(start=1,stop=1000000,step=5)  #very large number series
len(x)

200000

In [6]:
print(x[1:50])  # print from 1st position to 50th position
print()
print(x[1:50:10])  # print at interval of 10 starting 1st position to 50th position

[  6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91
  96 101 106 111 116 121 126 131 136 141 146 151 156 161 166 171 176 181
 186 191 196 201 206 211 216 221 226 231 236 241 246]

[  6  56 106 156 206]


In [10]:
print(np.mean(np.arange(1,50000000)))
#mean of np array of numbers from 1 to 10^7

25000000.0


In [15]:
np1 = np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(type(np1))
print(dir(np1), sep ='\t')

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [8]:
np.array(([1,2,3,4,10]))

NameError: name 'np' is not defined